version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - $PORT:$DOCKER_PORT
    env_file:
      - .env
    command: bash -c 'yarn typeorm migration:run -d ./src/data-source && yarn dev'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules

  db:
    container_name: db
    image: postgres:14.5
    ports:
      - $DB_PORT:$PGPORT
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
